#服务配置
server:
  #端口
  port: 9995
  #服务编码
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: zzyl
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 6MB
  #数据源配置
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/zzyl?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: ENC(TKiI5qeCTCepRTioxFvTrcifvVWMFX1/UbqmM43dQqbAN0AKyrBKBMXCdrKUCuoX)
# MyBatis配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath*:mapper*/*Mapper.xml
  type-aliases-package: com.zzyl.entity
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-statement-timeout: 60
    default-fetch-size: 100
logging:
  config: classpath:logback.xml
  level:
    org.springframework.web.socket: debug
knife4j:
  enable: true
zzyl:
  framework:
    swagger:
      swagger-path: com.zzyl.controller
      title: 智慧养老服务
      description: 智慧养老
      contact-name: 黑马研究院
      contact-url: www.itheima.com
      contact-email: itheima@itcast.cn
    jwt:
      base64-encoded-secret-key: $2a$10$PVtHnkj86mJgf6li/yron.LRx/cQAlaiZkBJ9BeogCNTryXJRT1YC
      ttl: 3600000
    oss:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      accessKeyId: ENC(Tqs0J9tMBprU1vAjXmoxK7hmrklHhOchwxWIlG002/ItB39r02eq/9j44hwlEwuHRdCuVnj5fVM+cmf3cL8QTg==)
      accessKeySecret: ENC(Bqfwgp0hKJyE6wpNsBPVR8mM0q1TEmiXrWb4B9SAwUeEbHNUaQV6LhItDjtsSq33XO4AXSaYUu/ZakXIzrL/NQ==)
      bucketName: java-li-web
  wechat:
    appId: ENC(bTkbTDjlbTqdSmd5E29+tywVCoEu7ysJUrq2BHD7ciwBjT7J64By8N1ymvvjV2bUo6OCBhd1pP3ksHr5TDMStA==)
    appSecret: ENC(cnwB1x56V42SXYpRQmRI+NNnVV4ucCLl+1zO4jbG0t0byLyMqTuBNpogMSMoOTK4pz6oTOqo8Zjn7E+PGa17rF+7vA1iCWtwEvdT+Ae056k=)
